spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/traditional-market
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
        show_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
#imgLocation: /Users/jiyun/Documents/git/Team4_Backend/Traditional-Market/images/
#uploadPath: file:///Users/jiyun/Documents/git/Team4_Backend/Traditional-Market/images/